{% set name = "watchgha" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchgha-{{ version }}.tar.gz
  sha256: 48eac25df88e7dc3a982ffe6d5056a57a67c542032452b1794605e55dd7366d0

build:
  entry_points:
    - watch_gha_runs = watchgha.watch_runs:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - click
    - exceptiongroup
    - httpx
    - rich
    - trio
    - dulwich

test:
  imports:
    - watchgha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nedbat/watchgha
  summary: Watch GitHub action runs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
