{% set name = "watchgha" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchgha-{{ version }}.tar.gz
  sha256: c156b33d667e1b60fe5babe170189b9111e8e3985ac174b78430471d7f7d6af6

build:
  entry_points:
    - watch_gha_runs = watchgha.watch_runs:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - click
    - exceptiongroup
    - httpx
    - rich
    - trio

test:
  imports:
    - watchgha
  commands:
    - pip check
    - watch_gha_runs --help
  requires:
    - pip

about:
  home: https://github.com/nedbat/watchgha
  summary: Watch GitHub action runs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
