{% set name = "watchgha" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/watchgha-{{ version }}.tar.gz
  sha256: 46d9820beb703a4faf89663b5936d3ceec474ccdcc3b0c3eb11b84be57a609c2
  patches:
    - pyproject.patch

build:
  entry_points:
    - watch_gha_runs = watchgha.watch_runs:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - exceptiongroup
    - httpx
    - rich
    - trio
    - dulwich

test:
  imports:
    - watchgha
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nedbat/watchgha
  summary: Watch GitHub action runs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
